"""Build the comprehensive scHopfield report for one dataset (notebooks 01-08 pipeline).

    PYTHONPATH=analyses/reports .venv/bin/python analyses/reports/build_report.py \
        --dataset paul15 --device cuda

Writes figure_packs/reports/<dataset>/{plots,data}/ + RESULTS.md.
"""
import argparse

from config import DATASETS
from rutils import prepare_and_fit, Report
import sections as S

SECTIONS = {}
for _k in ("A", "B", "C", "D", "E"):
    _fn = getattr(S, f"section_{_k}", None)
    if _fn is not None:
        SECTIONS[_k] = _fn


def build(name, device="cuda", force=False, only=None):
    cfg = DATASETS[name]
    ck = cfg["cluster_key"]
    adata = prepare_and_fit(name, device=device, force=force)
    rep = Report(name, f"scHopfield comprehensive report: {name}")
    rep.text(
        f"Full analysis pipeline (notebooks 01-08) for **{name}**. Dynamics inferred from "
        f"**{cfg['velocity_mode']}**. Fit: {adata.n_vars} top genes, species-appropriate "
        f"scaffold + L1 bias. All panels are regenerated by `analyses/reports/`."
    )
    for key in (only or ["A", "B", "C", "D", "E"]):
        fn = SECTIONS.get(key)
        if fn is None:
            continue
        print(f"[{name}] section {key}", flush=True)
        try:
            fn(adata, name, ck, rep, cfg)
        except Exception as exc:
            import traceback
            print(f"[{name}] SECTION {key} FAILED: {exc}", flush=True)
            traceback.print_exc()
    rep.write()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", required=True, choices=list(DATASETS) + ["all"])
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--force", action="store_true", help="re-fit even if cached")
    ap.add_argument("--sections", default=None, help="comma list e.g. A,B")
    args = ap.parse_args()
    only = args.sections.split(",") if args.sections else None
    names = list(DATASETS) if args.dataset == "all" else [args.dataset]
    for n in names:
        build(n, device=args.device, force=args.force, only=only)


if __name__ == "__main__":
    main()
